#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

//! FreeFlow Windows tray host (spike 1).
//!
//! The window is a thin shell: all transcription / update logic lives in the
//! dependency-free frontend (../frontend, reusing ../companion cores). This
//! binary owns the tray icon, Show/Quit menu, and hide-on-close behavior.

use tauri::menu::{Menu, MenuItem};
use tauri::tray::{MouseButton, MouseButtonState, TrayIconBuilder, TrayIconEvent};
use tauri::{Manager, WindowEvent};

fn main() {
    tauri::Builder::default()
        .setup(|app| {
            let show = MenuItem::with_id(app, "show", "Show", true, None::<&str>)?;
            let quit = MenuItem::with_id(app, "quit", "Quit", true, None::<&str>)?;
            let menu = Menu::with_items(app, &[&show, &quit])?;
            // Raw 32x32 RGBA generated by windows/scripts/make-icon.mjs.
            let icon = tauri::image::Image::new_owned(
                include_bytes!("../icons/tray-32.rgba").to_vec(),
                32,
                32,
            );
            TrayIconBuilder::new()
                .icon(icon)
                .tooltip("FreeFlow Windows")
                .menu(&menu)
                .on_menu_event(|app, event| match event.id.as_ref() {
                    "quit" => app.exit(0),
                    "show" => {
                        if let Some(window) = app.get_webview_window("main") {
                            let _ = window.show();
                            let _ = window.set_focus();
                        }
                    }
                    _ => {}
                })
                .on_tray_icon_event(|tray, event| {
                    if let TrayIconEvent::Click {
                        button: MouseButton::Left,
                        button_state: MouseButtonState::Up,
                        ..
                    } = event
                    {
                        let app = tray.app_handle();
                        if let Some(window) = app.get_webview_window("main") {
                            let _ = window.show();
                            let _ = window.set_focus();
                        }
                    }
                })
                .build(app)?;
            Ok(())
        })
        .on_window_event(|window, event| {
            if let WindowEvent::CloseRequested { api, .. } = event {
                // Tray app: closing the window hides it instead of quitting.
                let _ = window.hide();
                api.prevent_close();
            }
        })
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
